-- use uppercase names for Oracle defaults
CREATE TABLE USERS_JDBC (
    USERID VARCHAR2(200),
    PASSWORD VARCHAR2(200),
    NAME VARCHAR2(200),
    INCORRECTATTEMPTS NUMBER(2),
    LOCKSTATUS NUMBER(2),
    USERTYPE VARCHAR2(200)
);

-- Insert sample rows
INSERT INTO USERS_JDBC VALUES ('AB1001','AB1001','Hari',0,0,'Admin');
INSERT INTO USERS_JDBC VALUES ('TA1002','TA1002','Prasath',0,0,'Employee');
INSERT INTO USERS_JDBC VALUES ('RS1003','RS1003','Ganesh',0,0,'Employee');

COMMIT;
